### ISSUE TITLE
Release 1.0 in November

### ISSUE THREAD

**Issue by alex-oleshkevich** [alex-oleshkevich/starception#13]
Take 1 month and if no issues found release 1.0.

**Comment by euri10** [comment]
I've been using it extensively since and just found inadvertantly that little template error, I think this is ready

**Comment by alex-oleshkevich** [comment]
I am in doubt about theme switch button. Currently, it shows the next theme in the chain, not current. Looks like it is a bit confusing. Does it make sense to show current theme icon?

**Comment by euri10** [comment]
> I am in doubt about theme switch button. Currently, it shows the next theme in the chain, not current. Looks like it is a bit confusing. Does it make sense to show current theme icon?

I have to admit I didnt know that there was a theme switcher, after looking at it I think it's more natural to display current vs next, but that's a matter of taste I suppose, nothhing that should prevent a release :)

**Comment by euri10** [comment]
> Done! Time to open a few beers :)

well deserved it's been a pleasure to develop with it !
