### ISSUE TITLE
Syntax highlighting in the browser

### ISSUE THREAD

**Issue by jtraub** [alex-oleshkevich/starception#17]
What if we do syntax highlighting in the browser? Starception already uses js to switch between frames so moving syntax highlighting to the client side is something that can be considered.

I am evaluating [Highlight.js](https://github.com/highlightjs/highlight.js) for this. A custom build can be created that contains just two themes and highlighters for selected languages (python, js, html, (s)css) and then integrated into Starception.

This would allow us to drop `pygments` dependency and use `prefers-color-scheme`  media feature to automatically switch between light and dark themes. Lack of auto switching depending on day/night is the most irritating thing for me right now.

What are your thoughts @alex-oleshkevich ? Would you be willing to accept a PR with such change?

**Comment by alex-oleshkevich** [comment]
Yes, only modern browsers. That's an internal tool, so support near edge
browsers is reasonable.

**Comment by alex-oleshkevich** [comment]
I would like to defer any bundlers as late as possible and stick to vanilla JS embedding it into HTML response body.

**Comment by alex-oleshkevich** [comment]
@jtraub i have an idea how we (possibly) can reach it without the refactoring. 
What if we switch pygments to use classes instead of inline styles and embed two stylesheets into the HTML wrapped into media query? This will switch colors using your system settings.

**Comment by jtraub** [comment]
@alex-oleshkevich I was thinking about that before and there was something that stopped me from switching pygments back to classes. Let me check again in the morning.

If it would work I will simply do a PR instead.

**Comment by alex-oleshkevich** [comment]
@jtraub works perfectly.
Need more testing and polishing before merge.
https://github.com/alex-oleshkevich/starception/pull/22

**Comment by alex-oleshkevich** [comment]
Merged.
