### ISSUE TITLE
python interpreter in browser debugger?

### ISSUE THREAD

**Issue by msenol86** [alex-oleshkevich/starception#20]
Any plans to include werkzeug-like python interpreter to starception? We use docker and fastapi in our work environment. There fore we cannot use vscode or pycharm debugger. It would be great if we can drop into Python intertpreter via browser if an exception occurs.

**Comment by alex-oleshkevich** [comment]
I wish I could, but I don't know how it works ;) Maybe after some research it will be built-in, but not in the near future.

**Comment by alex-oleshkevich** [comment]
I am reopening it as it would be a good add-on to the library. However, the feature is not a priority and no any ETA unless someone Pars it.

**Comment by euri10** [comment]
> We use docker and fastapi in our work environment. There fore we cannot use vscode or pycharm debugger.

how so @msenol86 ? I'm using pycharm + fastapi + starception, and I cant remember the last time I didnt debug in a docker container

**Comment by msenol86** [comment]
> > We use docker and fastapi in our work environment. There fore we cannot use vscode or pycharm debugger.
> 
> how so @msenol86 ? I'm using pycharm + fastapi + starception, and I cant remember the last time I didnt debug in a docker container

I have tried starception but it only shows errors in browser, I cannot drop into Python interpreter like werkzeug on browser

**Comment by euri10** [comment]
in pycharm you just use the remote interpreter ie the interpreter your container runs on and that's pretty much it, it stops at breakpoints, you inspect variables etc...
not sure about vscode I never used it

**Comment by msenol86** [comment]
> in pycharm you just use the remote interpreter ie the interpreter your container runs on and that's pretty much it, it stops at breakpoints, you inspect variables etc... not sure about vscode I never used it

ok i will try that thank you very much
