### ISSUE TITLE
secrets in url / db uri

### ISSUE THREAD

**Issue by euri10** [alex-oleshkevich/starception#9]
what do you think of having url / uri keywords added to masked_secrets as they often contains passwords for redis, postgresql etc or maybe have an option to not display some added keywords

**Comment by alex-oleshkevich** [comment]
I will replace password component of URLs with stars. 
Custom keyword is a good idea too, for later ;)

**Comment by alex-oleshkevich** [comment]
let me know if it works for you

**Comment by euri10** [comment]
> let me know if it works for you

yep, thats cool now in env var

`redis://:********@backend_redis:6379`
